<script setup lang="ts">
import type { NyxFission } from 'nyx-fission'

const portrait = useTemplateRef<HTMLDivElement>('portrait')
const canvas = useTemplateRef<HTMLCanvasElement>('canvas')
const baseURL = useRuntimeConfig().app.baseURL
const isReady = ref(false)

let instance: NyxFission | undefined
let observer: IntersectionObserver | undefined
let motionQuery: MediaQueryList | undefined
let isVisible = false
let isMounted = false
let generation = 0

const stop = () => {
  generation += 1
  isReady.value = false
  instance?.destroy()
  instance = undefined
}

const update = async () => {
  stop()
  if (!isMounted || !isVisible || document.hidden || motionQuery?.matches) return

  const currentGeneration = generation
  try {
    const { NyxFission, MediaType, LumaKeyMode, ThemeName, NyxEvent } = await import('nyx-fission')
    if (currentGeneration !== generation || !canvas.value) return

    const particles = new NyxFission({
      // Turns at 1×, rests at 0.5×; generated by scripts/retime-hero-portrait.py.
      source: `${baseURL}videos/portrait1-paced.mp4`,
      type: MediaType.Video,
      theme: ThemeName.Nyx,
      depth: 0.1,
      lumaKey: { mode: LumaKeyMode.Light, threshold: 0.2, coherence: 0.1 },
    })
    instance = particles
    particles.on(NyxEvent.Error, () => {
      if (instance === particles) stop()
    })
    particles.mount(canvas.value)
    await particles.ready
    if (currentGeneration === generation) isReady.value = true
  }
  catch {
    // Leave the portrait empty when media playback or WebGL is unavailable.
    if (currentGeneration === generation) stop()
  }
}

onMounted(() => {
  isMounted = true
  motionQuery = window.matchMedia('(prefers-reduced-motion: reduce)')
  motionQuery.addEventListener('change', update)
  document.addEventListener('visibilitychange', update)
  observer = new IntersectionObserver(([entry]) => {
    const visible = entry?.isIntersecting ?? false
    if (visible === isVisible) return
    isVisible = visible
    void update()
  })
  if (portrait.value) observer.observe(portrait.value)
})

onBeforeUnmount(() => {
  isMounted = false
  observer?.disconnect()
  motionQuery?.removeEventListener('change', update)
  document.removeEventListener('visibilitychange', update)
  stop()
})
</script>

<template>
  <div ref="portrait" class="hero-portrait" :class="{ 'hero-portrait--ready': isReady }" :role="isReady ? 'img' : undefined" :aria-label="isReady ? 'Portrait of Arne Decant' : undefined">
    <canvas ref="canvas" class="hero-portrait__canvas" aria-hidden="true" />
  </div>
</template>

<style scoped lang="scss">
.hero-portrait {
  position: relative;
  width: min(100%, 32rem);
  aspect-ratio: 3 / 4;
  justify-self: end;
  overflow: hidden;
  pointer-events: none;
  // Transparent gutters hide boundary particles before the fades begin,
  // including at fractional canvas sizes and browser zoom levels.
  mask-image:
    linear-gradient(transparent 4%, black 16%, black 85%, transparent),
    linear-gradient(90deg, transparent 4%, black 18%, black 82%, transparent 96%);
  mask-composite: intersect;
}

.hero-portrait__canvas {
  display: block;
  width: 100%;
  height: 100%;
  position: absolute;
  inset: 0;
  opacity: 0;
  // Crop the source video's letterboxing out of the visible portrait.
  transform: scale(1.5);
}

.hero-portrait--ready {
  .hero-portrait__canvas { opacity: 1; }
}
</style>
